---
- hosts: webservers
  become: yes
  tasks:
    - name: Actualizar cache de apt
      apt: update_cache=yes force_apt_get=yes

    - name: Instalar Apache
      apt: name=apache2 state=present

    - name: Instalar Cowsay
      apt: name=cowsay state=present

    - name: Crear un archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /vagrant/mensaje.txt
        dest: /home/vagrant/mensaje.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/nueva_carpeta
        state: directory

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: nuevo_usuario
        state: present
        shell: /bin/bash

    - name: Ejecutar un script
      command: /home/vagrant/script.sh
